apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-server-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  SERVER_PORT: "{{ .Values.server.port }}"
  SERVER_VERSION: "{{ .Values.server.version }}"
  DB_HOST: "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc"
  DB_PORT: "5432"
  DB_NAME: "{{ .Values.postgresql.auth.database }}"
  DB_USER: "{{ .Values.postgresql.auth.username }}"
  DB_PASSWORD: "{{ .Values.postgresql.auth.password }}"
