image:
  repository: rnrmf
  name: smashup-indicator-service
  pullPolicy: IfNotPresent
  tag: 6
replicaCount: 1
protocol: TCP
service:
  type: NodePort
  port: 8085
namespace: indicator
container:
  name: indicator-service-container
  port: 8085