apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository}}/{{ .Values.image.name }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: spring.profiles.active
              value: "prod"
            - name: PROD_MONGODB_DATABASE
              value: "smashup_indicator_db"
            - name: PROD_MONGODB_USERNAME
              value: "root"
            - name: PROD_MONGODB_PASSWORD
              value: "bX0QszlA2mN0VSDXdn2m"
            - name: PROD_MONGODB_HOST
              value: mongo-0.indicator-mongo-service.indicator.svc.cluster.local
            - name: PROD_MONGODB_PORT
              value: "27017"
