apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: indicator-mongo-service
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "bX0QszlA2mN0VSDXdn2m"
            - name: MONGO_INITDB_DATABASE
              value: "smashup_indicator_db"
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: volume-mongo
              mountPath: /var/lib/mongo
  volumeClaimTemplates:
    - metadata:
        name: volume-mongo
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
